#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'
require 'did_you_mean'
require 'optparse'
require 'yaml'

TAXONOMY_PATH = 'data/tag_taxonomy.yml'
CONTENT_GLOB = 'content/[0-9][0-9][0-9][0-9]/[0-9][0-9]/[0-9][0-9]/*/index{,.en}.md'

OPTIONS = {
  check: false,
  search: nil,
  write: nil
}.freeze

def parse_options
  options = OPTIONS.dup
  OptionParser.new do |parser|
    parser.banner = 'Usage: scripts/tag_catalog.rb [options]'
    parser.on('--search QUERY', 'Find canonical tags by name, alias, or meaning') { |value| options[:search] = value }
    parser.on('--check', 'Validate all published PT and EN post tags') { options[:check] = true }
    parser.on('--write PATH', 'Write the full Markdown catalog to PATH') { |value| options[:write] = value }
  end.parse!
  options
end

def taxonomy_data
  @taxonomy_data ||= YAML.safe_load_file(TAXONOMY_PATH)
end

def normalize(value)
  value.to_s
       .unicode_normalize(:nfkd)
       .gsub(/\p{Mn}/, '')
       .downcase
       .gsub(/[^a-z0-9]+/, ' ')
       .strip
end

def tag_entries
  taxonomy_data.fetch('tags').map do |id, values|
    {
      id: id,
      pt: values.fetch('pt'),
      en: values.fetch('en'),
      description: values.fetch('description'),
      kind: values.fetch('kind', 'topic'),
      aliases: Array(values['aliases'])
    }
  end
end

def markdown_escape(value)
  value.to_s.gsub('|', '\\|').gsub("\n", ' ')
end

def render_table(entries)
  lines = [
    '| PT-BR | English | Purpose | Known aliases |',
    '|---|---|---|---|'
  ]
  entries.each do |entry|
    aliases = entry[:aliases].empty? ? '-' : entry[:aliases].join(', ')
    lines << "| `#{markdown_escape(entry[:pt])}` | `#{markdown_escape(entry[:en])}` | #{markdown_escape(entry[:description])} | #{markdown_escape(aliases)} |"
  end
  lines
end

def render_catalog
  entries = tag_entries
  projects = entries.select { |entry| %w[project series].include?(entry[:kind]) }
  topics = entries.reject { |entry| %w[project series].include?(entry[:kind]) }
  events = taxonomy_data.fetch('event_series').map do |slug, values|
    { pt: slug, en: slug, description: 'One named event edition or recurring event series.', aliases: values.fetch('aliases') }
  end
  special = taxonomy_data.fetch('special_tags').map do |id, values|
    { pt: values.fetch('pt'), en: values.fetch('en'), description: "Reserved section tag (#{id}).", aliases: [] }
  end

  lines = [
    '# Tag Catalog',
    '',
    'Generated from `data/tag_taxonomy.yml`. Do not edit this file directly.',
    '',
    'Before tagging a new article, search the catalog:',
    '',
    '```bash',
    './scripts/tag_catalog.rb --search "article title and central subjects"',
    '```',
    '',
    'Reuse existing canonical tags. Add a new tag to the YAML only when it will identify a real recurring project, series, event edition, or cohesive subject that no existing tag covers. Never create spelling, plural, capitalization, or language variants.',
    '',
    "## Projects And Series (#{projects.length})",
    '',
    *render_table(projects),
    '',
    "## Topics (#{topics.length})",
    '',
    *render_table(topics),
    '',
    "## Event Editions (#{events.length})",
    '',
    *render_table(events),
    '',
    "## Reserved Tags (#{special.length})",
    '',
    *render_table(special),
    ''
  ]
  lines.join("\n")
end

def search_catalog(query)
  normalized_query = normalize(query)
  tokens = normalized_query.split.reject { |token| token.length < 3 }
  matches = tag_entries.filter_map do |entry|
    fields = [entry[:id], entry[:pt], entry[:en], entry[:description], *entry[:aliases]].map { |value| normalize(value) }
    exact = fields.include?(normalized_query)
    phrase = fields.any? { |field| field.include?(normalized_query) }
    token_hits = tokens.count { |token| fields.any? { |field| field.include?(token) } }
    score = (exact ? 100 : 0) + (phrase ? 40 : 0) + token_hits
    [score, entry] if score.positive?
  end

  matches.sort_by { |score, entry| [-score, entry[:pt]] }.first(15).map do |_score, entry|
    aliases = entry[:aliases].empty? ? '' : " | aliases: #{entry[:aliases].join(', ')}"
    "#{entry[:pt]} -> #{entry[:en]} | #{entry[:description]}#{aliases}"
  end
end

def parse_frontmatter(path)
  content = File.read(path)
  match = content.match(/\A---[ \t]*\r?\n(.*?)\r?\n---[ \t]*\r?\n/m)
  raise "Missing YAML frontmatter in #{path}" unless match

  YAML.safe_load(match[1], permitted_classes: [Date, Time], aliases: true) || {}
end

def published?(frontmatter)
  frontmatter['draft'] != true && DateTime.parse(frontmatter.fetch('date').to_s) <= DateTime.now
rescue KeyError, Date::Error
  false
end

def language_maps
  maps = { 'pt' => {}, 'en' => {} }
  taxonomy_data.fetch('tags').each do |id, values|
    maps['pt'][values.fetch('pt')] = id
    maps['en'][values.fetch('en')] = id
  end
  taxonomy_data.fetch('event_series').each_key do |slug|
    maps['pt'][slug] = "event:#{slug}"
    maps['en'][slug] = "event:#{slug}"
  end
  taxonomy_data.fetch('special_tags').each do |id, values|
    maps['pt'][values.fetch('pt')] = "special:#{id}"
    maps['en'][values.fetch('en')] = "special:#{id}"
  end
  maps
end

def check_catalog
  maps = language_maps
  failures = []
  published = {}

  Dir.glob(CONTENT_GLOB).sort.each do |path|
    frontmatter = parse_frontmatter(path)
    next unless published?(frontmatter)

    language = path.end_with?('.en.md') ? 'en' : 'pt'
    tags = Array(frontmatter['tags']).map(&:to_s)
    failures << "#{path}: no tags" if tags.empty?
    unknown = tags - maps.fetch(language).keys
    unless unknown.empty?
      spellchecker = DidYouMean::SpellChecker.new(dictionary: maps.fetch(language).keys)
      unknown.each do |tag|
        suggestions = spellchecker.correct(tag).first(3)
        hint = suggestions.empty? ? '' : "; did you mean #{suggestions.map { |value| "`#{value}`" }.join(', ')}?"
        failures << "#{path}: unknown #{language.upcase} tag `#{tag}`#{hint}"
      end
    end
    published[path] = tags
  end

  published.each do |path, pt_tags|
    next if path.end_with?('.en.md')

    en_path = path.sub(/index\.md\z/, 'index.en.md')
    next unless published.key?(en_path)

    pt_ids = pt_tags.map { |tag| maps['pt'][tag] }
    en_ids = published.fetch(en_path).map { |tag| maps['en'][tag] }
    failures << "#{path}: PT/EN tag mismatch" unless pt_ids == en_ids
  end

  if failures.empty?
    puts "Tag catalog check passed for #{published.length} published files."
    return true
  end

  warn failures.join("\n")
  false
end

options = parse_options
success = check_catalog if options[:check]

if options[:search]
  results = search_catalog(options[:search])
  puts(results.empty? ? 'No matching canonical tags.' : results)
elsif options[:write]
  File.write(options[:write], render_catalog)
  puts "Wrote #{options[:write]}"
elsif !options[:check]
  puts render_catalog
end

exit 1 if options[:check] && !success
